// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftknrzbgywucuodiaayt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0a25yemJneXd1Y3VvZGlhYXl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzMjkzOTYsImV4cCI6MjA3ODkwNTM5Nn0.Q0iJaI3Mnv-2S_--hQKj7zgS_lVlMwIL0jkhDqfN6tI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});